<?php

/**
 * @file
 * Contains planet_project.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function planet_project_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the planet_project module.
    case 'help.page.planet_project':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Planet Drupal projects related code.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function planet_project_theme() {
  return [
    'planet_project' => [
      'render element' => 'children',
    ],
  ];
}
